pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=Evaluate flake.nix
      - check-success=package nix-eval-jobs [x86_64-linux]
      - check-success=devShell default [x86_64-linux]
      - check-success=check treefmt [x86_64-linux]
      - check-success=package default [x86_64-linux]
      - check-success=tests (ubuntu-latest)
      - check-success=tests (macos-latest)
      - author=nix-eval-jobs-bot
    actions:
      merge:
        method: merge
      delete_head_branch: {}
