name: "Flake test"
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron:  '51 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v15
    - name: List flake structure
      run: nix flake show
    - name: Build
      run: nix build --out-link result
    - name: Run tests
      run: |
        nix develop -c install -D ./result/bin/nix-eval-jobs ./build/src/nix-eval-jobs
        nix develop -c pytest ./tests
